version: '3.4'

services:
  reservation.api:
    image: ${DOCKER_REGISTRY-}reservationapi
    container_name: Reservation.Api
    build:
      context: .
      dockerfile: src/Reservation.Api/Dockerfile
    depends_on:
      - reservation-db

  reservation-db:
    image: postgres:latest
    container_name: Reservation.Db
    environment:
      - POSTGRES_DB=reservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  reservation-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Reservation.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/reservation-realm-export.json
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/reservation-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080